services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: myprojectdb
      POSTGRES_USER: myprojectuser
      POSTGRES_PASSWORD: myprojectpassword
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/  # Ma'lumotlarni hostda saqlash
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myprojectuser -d myprojectdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://myprojectuser:myprojectpassword@db:5432/myprojectdb

