# Generated by Django 4.1.7 on 2023-03-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
