# Generated by Django 4.1.7 on 2023-03-10 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='direc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='direc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
