# Generated by Django 4.1.7 on 2023-03-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_day',
        ),
        migrations.AddField(
            model_name='experience',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
