# Generated by Django 4.1.7 on 2023-03-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_remove_experience_end_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='end_day',
        ),
        migrations.AddField(
            model_name='education',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
