# Generated by Django 4.1.7 on 2023-03-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_blog_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='from_who',
        ),
    ]
