# Generated by Django 4.1.7 on 2023-03-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_rename_messege_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('about', models.TextField()),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
