# Generated by Django 4.2.6 on 2023-10-04 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_about_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='instagram_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='telegram_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
