# Generated by Django 4.2.6 on 2023-10-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_about_instagram_user_about_telegram_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
