# Generated by Django 5.0.9 on 2024-12-28 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_alter_about_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='github_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
